// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b9601ab2-a575-4dc3-8d70-d0b16b788137",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Qq41muZYV",
    "aws_user_pools_web_client_id": "1c2nvilfr35l550a553b9iic6f",
    "aws_content_delivery_bucket": "gatsbyauth-20180816145726-hosting-bucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://gatsbyauth-20180816145726-hosting-bucket.s3.amazonaws.com"
};


export default awsmobile;
