// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2507ac85-210e-4ac2-811f-710921e79975",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_beRjEHgNx",
    "aws_user_pools_web_client_id": "4859koinfvto1qt6gnmqn67gfq"
};


export default awsmobile;
